package ro.gs1.log4e2026.preferences;

/**
 * Interface containing all preference key constants used throughout the Log4E plugin.
 * These keys are used for both workspace-level and project-level preferences.
 */
public interface PreferenceKeys {

    // Template placeholder variables
    String PROF_LOGGER = "${logger}";
    String PROF_DELIMITER = "${delimiter}";
    String PROF_DELIMITER_MSG = "${delimiter_msg}";
    String PROF_SOURCEMETHOD = "${enclosing_method}";
    String PROF_SOURCEMETHOD_WITH_PLACEHOLDERS = "${enclosing_method_with_placeholders}";
    String PROF_SOURCEMETHOD_ARGUMENTS = "${enclosing_method_arguments}";
    String PROF_SOURCEMETHOD_ARGUMENT_PLACEHOLDERS = "${enclosing_method_argument_placeholders}";
    String PROF_SOURCEMETHOD_ARGUMENTS_AS_PARAMETERS = "${enclosing_method_arguments_as_parameters}";
    String PROF_SOURCEMETHOD_ONLY = "${enclosing_method_only}";
    String PROF_ENCLOSING_PACKAGE = "${enclosing_package}";
    String PROF_SOURCECLASS = "${enclosing_type}";
    String PROF_EXCEPTION = "${exception}";
    String PROF_LOCALVARS = "${localvars}";
    String PROF_MESSAGE = "${message}";
    String PROF_MESSAGE_USER = "${message_user}";
    String PROF_RETURNVALUE = "${return_value}";
    String PROF_RETURNVALUE_PLACEHOLDER = "${return_value_placeholder}";
    String PROF_RETURNVALUE_AS_PARAMETER = "${return_value_as_parameter}";
    String PROF_RETURNTYPE = "${return_type}";
    String PROF_VARIABLES = "${variables}";
    String PROF_VARIABLE_PLACEHOLDERS = "${variable_placeholders}";
    String PROF_VARIABLES_AS_PARAMETERS = "${variables_as_parameters}";

    // Arrays of template variables for different contexts
    String[] PROF_TEMPLATE_VARIABLES = {
        PROF_DELIMITER, PROF_DELIMITER_MSG, PROF_SOURCEMETHOD,
        PROF_SOURCEMETHOD_WITH_PLACEHOLDERS, PROF_SOURCEMETHOD_ONLY,
        PROF_SOURCEMETHOD_ARGUMENTS, PROF_SOURCEMETHOD_ARGUMENT_PLACEHOLDERS,
        PROF_SOURCEMETHOD_ARGUMENTS_AS_PARAMETERS, PROF_ENCLOSING_PACKAGE,
        PROF_SOURCECLASS, PROF_EXCEPTION, PROF_LOGGER, PROF_MESSAGE,
        PROF_MESSAGE_USER, PROF_RETURNVALUE, PROF_RETURNVALUE_PLACEHOLDER,
        PROF_RETURNVALUE_AS_PARAMETER, PROF_RETURNTYPE, PROF_VARIABLES,
        PROF_VARIABLE_PLACEHOLDERS, PROF_VARIABLES_AS_PARAMETERS
    };

    String[] PROF_TEMPLATE_INITIALIZER_VARIABLES = {
        PROF_DELIMITER, PROF_DELIMITER_MSG, PROF_ENCLOSING_PACKAGE,
        PROF_SOURCECLASS, PROF_LOGGER
    };

    // Scope and profile settings
    String PREFERENCES_SCOPE = "PREFERENCES_SCOPE";
    String LOGGER_DEFAULT = "LOGGER_DEFAULT";
    String LOGGER_PROFILE = "LOGGER_PROFILE";
    String PROJECTS = "PROJECTS";

    // Declaration settings
    String AUTOMATIC_IMPORTS = "AUTOMATIC_IMPORTS";
    String TASK_IMPORTS = "TASK_IMPORTS";
    String LOGGER_IMPORTS = "LOGGER_IMPORTS";
    String AUTOMATIC_DECLARE = "AUTOMATIC_DECLARE";
    String AUTOMATIC_DECLARE_INNER_CLASSES = "AUTOMATIC_DECLARE_INNER_CLASSES";
    String TASK_DECLARE = "TASK_DECLARE";
    String REAPPLY_DECLARE = "REAPPLY_DECLARE";
    String CREATE_COMMENTS = "CREATE_COMMENTS";
    String CREATE_COMMENTS_ONELINE = "CREATE_COMMENTS_ONELINE";
    String LOGGER_COMMENT = "LOGGER_COMMENT";
    String STATIC_FLAG = "STATIC_FLAG";
    String FINAL_FLAG = "FINAL_FLAG";
    String ACCESS_FLAG = "ACCESS_FLAG";
    String LOGGER_NAME = "LOGGER_NAME";
    String LOGGER_TYPE = "LOGGER_TYPE";
    String LOGGER_INITIALIZER = "LOGGER_INITIALIZER";

    // Log level enabled flags
    String FINEST_ENABLED = "FINEST_ENABLED";
    String FINER_ENABLED = "FINER_ENABLED";
    String TRACE_ENABLED = "TRACE_ENABLED";
    String DEBUG_ENABLED = "DEBUG_ENABLED";
    String INFO_ENABLED = "INFO_ENABLED";
    String WARN_ENABLED = "WARN_ENABLED";
    String ERROR_ENABLED = "ERROR_ENABLED";
    String FATAL_ENABLED = "FATAL_ENABLED";
    String START_ENABLED = "START_ENABLED";
    String END_ENABLED = "END_ENABLED";
    String CATCH_ENABLED = "CATCH_ENABLED";
    String ENABLED_BRACES = "ENABLED_BRACES";

    // Logger statement templates per level
    String LOGGER_FINEST_STATEMENT = "LOGGER_FINEST_STATEMENT";
    String LOGGER_FINER_STATEMENT = "LOGGER_FINER_STATEMENT";
    String LOGGER_TRACE_STATEMENT = "LOGGER_TRACE_STATEMENT";
    String LOGGER_DEBUG_STATEMENT = "LOGGER_DEBUG_STATEMENT";
    String LOGGER_INFO_STATEMENT = "LOGGER_INFO_STATEMENT";
    String LOGGER_WARN_STATEMENT = "LOGGER_WARN_STATEMENT";
    String LOGGER_ERROR_STATEMENT = "LOGGER_ERROR_STATEMENT";
    String LOGGER_FATAL_STATEMENT = "LOGGER_FATAL_STATEMENT";

    // Is-enabled check statements per level
    String LOGGER_IS_FINEST_ENABLED_STATEMENT = "LOGGER_IS_FINEST_ENABLED_STATEMENT";
    String LOGGER_IS_FINER_ENABLED_STATEMENT = "LOGGER_IS_FINER_ENABLED_STATEMENT";
    String LOGGER_IS_TRACE_ENABLED_STATEMENT = "LOGGER_IS_TRACE_ENABLED_STATEMENT";
    String LOGGER_IS_DEBUG_ENABLED_STATEMENT = "LOGGER_IS_DEBUG_ENABLED_STATEMENT";
    String LOGGER_IS_INFO_ENABLED_STATEMENT = "LOGGER_IS_INFO_ENABLED_STATEMENT";
    String LOGGER_IS_WARN_ENABLED_STATEMENT = "LOGGER_IS_WARN_ENABLED_STATEMENT";
    String LOGGER_IS_ERROR_ENABLED_STATEMENT = "LOGGER_IS_ERROR_ENABLED_STATEMENT";
    String LOGGER_IS_FATAL_ENABLED_STATEMENT = "LOGGER_IS_FATAL_ENABLED_STATEMENT";

    // Position-specific statements
    String LOGGER_POS_START_STATEMENT = "LOGGER_POS_START_STATEMENT";
    String LOGGER_POS_END_STATEMENT = "LOGGER_POS_END_STATEMENT";
    String LOGGER_POS_CATCH_STATEMENT = "LOGGER_POS_CATCH_STATEMENT";
    String LOGGER_POS_IS_START_STATEMENT = "LOGGER_POS_IS_START_STATEMENT";
    String LOGGER_POS_IS_END_STATEMENT = "LOGGER_POS_IS_END_STATEMENT";
    String LOGGER_POS_IS_CATCH_STATEMENT = "LOGGER_POS_IS_CATCH_STATEMENT";

    // Exception handling
    String ERROR_EXCEPTION = "ERROR_EXCEPTION";
    String FATAL_EXCEPTION = "FATAL_EXCEPTION";
    String LOGGER_FORMAT_VARIABLE_PLACEHOLDER = "LOGGER_FORMAT_VARIABLE_PLACEHOLDER";

    // Format settings
    String FORMAT_DELIMITER = "FORMAT_DELIMITER";
    String FORMAT_DELIMITER_MSG = "FORMAT_DELIMITER_MSG";
    String FORMAT_RETURN_VALUE_NAME = "FORMAT_RETURN_VALUE_NAME";
    String FORMAT_ARGS_EMPTY_NAME = "FORMAT_ARGS_EMPTY_NAME";
    String FORMAT_PARENTHESIS_OPEN = "FORMAT_PARENTHESIS_OPEN";
    String FORMAT_PARENTHESIS_CLOSE = "FORMAT_PARENTHESIS_CLOSE";
    String FORMAT_EQUALS_SYMBOL = "FORMAT_EQUALS_SYMBOL";
    String FORMAT_DELIMITER_PARAM = "FORMAT_DELIMITER_PARAM";
    String FORMAT_ONE_LINE = "FORMAT_ONE_LINE";
    String FORMAT_USE_STRING_GENERATOR = "FORMAT_USE_STRING_GENERATOR";
    String FORMAT_STRING_GENERATOR_CLASS = "FORMAT_STRING_GENERATOR_CLASS";
    String FORMAT_STRING_STYLE = "FORMAT_STRING_STYLE";
    String FORMAT_STRING_GENERATOR_PARAMETER1 = "FORMAT_STRING_GENERATOR_PARAMTER1";

    // Replace settings (System.out/err replacement)
    String REPLACE_SOUT_LEVEL = "REPLACE_SOUT_LEVEL";
    String REPLACE_SERR_LEVEL = "REPLACE_SERR_LEVEL";
    String REPLACE_SOUT_ENABLED = "REPLACE_SOUT_ENABLED";
    String REPLACE_SERR_ENABLED = "REPLACE_SERR_ENABLED";
    String REPLACE_STACK_TRACE_ENABLED = "REPLACE_STACK_TRACE_ENABLED";
    String REPLACE_STACK_TRACE_STREAM = "REPLACE_STACK_TRACE_STREAM";

    // Miscellaneous settings
    String INNER_CLASSES_ENABLED = "INNER_CLASSES_ENABLED";
    String ADD_NON_NLS = "ADD_NON_NLS";
    String ANONYMOUS_CLASS_ENABLED = "ANONYMOUS_CLASS_ENABLED";
    String JDK15_ENABLED = "JDK15_ENABLED";
    String ECLIPSE_API_VERSION = "ECLIPSE_API_VERSION";

    // Position types
    String POS_START = "POS_START";
    String POS_END = "POS_END";
    String POS_CATCH = "POS_CATCH";
    String POS_EMPTY_CATCH = "POS_EMPTY_CATCH";
    String POS_OTHER = "POS_OTHER";

    // Position attribute suffixes (appended to position type)
    String POS_ATT_DISABLE_ADD_LOGGING = "_DISABLE_ADD_LOGGING";
    String POS_ATT_LEVEL = "_LEVEL";
    String POS_ATT_MSG = "_MSG";
    String POS_ATT_MSG_USER = "_MSG_USER";
    String POS_ATT_CONFIRM_INSERT = "_CONFIRM_INSERT";
    String POS_ATT_CONFIRM_MODIFY = "_CONFIRM_MODIFY";
    String POS_ATT_SKIP_CONSTRUCTOR = "_SKIP_CONSTRUCTOR";
    String POS_ATT_SKIP_EMPTY_METHODS = "_SKIP_EMPTY_METHODS";
    String POS_ATT_SKIP_GETTER = "_SKIP_GETTER";
    String POS_ATT_SKIP_SETTER = "_SKIP_SETTER";
    String POS_ATT_SKIP_TO_STRING = "_SKIP_TO_STRING";
    String POS_ATT_SKIP_SAME_EXCEPTION = "_SKIP_SAME_EXCEPTION";
    String POS_ATT_SKIP_EMPTY_CATCH_BLOCK = "_SKIP_EMPTY_CATCH_BLOCK";
    String POS_ATT_CATCH_BLOCK_LEVEL = "_CATCH_BLOCK_LEVEL";
    String POS_ATT_CATCH_BLOCK_MSG = "_CATCH_BLOCK_MSG";
    String POS_ATT_POSITION_LOGGER = "_POSITION_LOGGER";
    String POS_ATT_METHOD_INFO = "_METHOD_INFO";
    String POS_ATT_PARAMTYPES = "_PARAMTYPES";
    String POS_ATT_PARAMNAMES = "_PARAMNAMES";
    String POS_ATT_PARAMVALUES = "_PARAMVALUES";
    String POS_ATT_RETURN_REPLACEMENT = "_RETURN_REPLACEMENT";
    String POS_ATT_RETURN_VALUE = "_RETURN_VALUE";
    String POS_ATT_GREEDY = "_GREEDY";

    // UI settings
    String UI_SUCCESS_DIALOG = "UI_SUCCESS_DIALOG";
    String UI_DECLARE_C_WIZARD = "UI_DECLARE_C_WIZARD";
    String UI_DECLARE_CC_WIZARD = "UI_DECLARE_CC_WIZARD";
    String UI_INSERT_M_WIZARD = "UI_INSERT_M_WIZARD";
    String UI_INSERT_C_WIZARD = "UI_INSERT_C_WIZARD";
    String UI_REPLACE_M_WIZARD = "UI_REPLACE_M_WIZARD";
    String UI_REPLACE_C_WIZARD = "UI_REPLACE_C_WIZARD";
    String UI_MODIFY_M_WIZARD = "UI_MODIFY_M_WIZARD";
    String UI_MODIFY_C_WIZARD = "UI_MODIFY_C_WIZARD";
    String UI_REMOVE_M_WIZARD = "UI_REMOVE_M_WIZARD";
    String UI_REMOVE_C_WIZARD = "UI_REMOVE_C_WIZARD";
    String UI_EXCHANGE_C_WIZARD = "UI_EXCHANGE_C_WIZARD";
    String UI_CONFIRMATION = "UI_CONFIRMATION";
    String UI_OUTPUT_ENABLED = "UI_OUTPUT_ENABLED";
    String UI_OUTPUT = "UI_CONSOLE_OUTPUT";
    String UI_OPTION_OUTPUT_CONSOLE = "console";
    String UI_OPTION_OUTPUT_WINDOW = "window";
    String UI_CONSOLE_ACTIVATE = "UI_CONSOLE_ACTIVATE";

    // Log levels enum values
    String LEVEL_FINEST = "FINEST";
    String LEVEL_FINER = "FINER";
    String LEVEL_TRACE = "TRACE";
    String LEVEL_DEBUG = "DEBUG";
    String LEVEL_INFO = "INFO";
    String LEVEL_WARN = "WARN";
    String LEVEL_ERROR = "ERROR";
    String LEVEL_FATAL = "FATAL";

    // All log levels array
    String[] LOG_LEVELS = {
        LEVEL_FINEST, LEVEL_FINER, LEVEL_TRACE, LEVEL_DEBUG,
        LEVEL_INFO, LEVEL_WARN, LEVEL_ERROR, LEVEL_FATAL
    };
}
